name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd ~/MERN-E-Commerce-Store

            git pull origin main

            cd backend
            npm install

            cd ../frontend
            npm install
            npm run build

            pm2 restart ecommerce-backend

            sudo systemctl restart nginx